services:
  miniflux-db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - web_network
    environment:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: ${MINIFLUX_DB_PASS}
      POSTGRES_DB: miniflux
    volumes:
      - ${DATA_ROOT}/miniflux/db:/var/lib/postgresql/data

  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    networks:
      - web_network
    depends_on:
      - miniflux-db
    ports:
      - "9090:8080"
    environment:
      - DATABASE_URL=postgres://miniflux:${MINIFLUX_DB_PASS}@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASS}
      - POLLING_FREQUENCY=60

networks:
  web_network:
    external: true